repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
      - id: lint
        name: lint
        entry: make lint
        language: system
